name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v18
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix develop --command make --output-sync=target check
